spring:
    datasource:
      driver-class-name: org.postgresql.Driver
      url: ${DATASOURCE_URL}
      username: ${DATASOURCE_USERNAME}
      password: ${DATASOURCE_PASSWORD}
    jpa:
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
    devtools:
      restart:
        enabled: false
server:
  port: 8888
  servlet:
    context-path: /helper-bot
telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    username: ${TELEGRAM_BOT_USERNAME}
    person-id: ${TELEGRAM_PERSON_ID}
    admin-person-id: ${ADMIN_TELEGRAM_PERSON_ID}
chat-gpt:
  token: ${CHAT_GPT_TOKEN}
openai:
  api:
    url: https://api.openai.com/v1/chat/completions